import { ITeamData } from "./Interface/TeamData";

export const TeamsData:ITeamData[] = [
  {
    id: 1,
    rank: 1,
    points: 32,
    teamName: "Team Alpha",
    captainName: "Sanjay Singhania",
    captainImage: "Ellipse810",
  },
  {
    id: 2,
    rank: 2,
    points: 28,
    teamName: "Team Bravo",
    captainName: "John Doe",
    captainImage: "Ellipse810",
  },
  {
    id: 3,
    rank: 3,
    points: 35,
    teamName: "Team Charlie",
    captainName: "Alice Smith",
    captainImage: "Ellipse810",
  },
  {
    id: 4,
    rank: 4,
    points: 40,
    teamName: "Team Delta",
    captainName: "Bob Johnson",
    captainImage: "Ellipse810",
  },
  {
    id: 5,
    rank: 5,
    points: 36,
    teamName: "Team Echo",
    captainName: "Eve Williams",
    captainImage: "Ellipse810",
  },
  {
    id: 6,
    rank: 6,
    points: 29,
    teamName: "Team Foxtrot",
    captainName: "Charlie Brown",
    captainImage: "Ellipse810",
  },
  {
    id: 7,
    rank: 7,
    points: 33,
    teamName: "Team Golf",
    captainName: "David Davis",
    captainImage: "Ellipse810",
  },
  {
    id: 8,
    rank: 8,
    points: 31,
    teamName: "Team Hotel",
    captainName: "Frank White",
    captainImage: "Ellipse810",
  },
  {
    id: 9,
    rank: 9,
    points: 34,
    teamName: "Team India",
    captainName: "Grace Jackson",
    captainImage: "Ellipse810",
  },
  {
    id: 10,
    rank: 10,
    points: 10,
    teamName: "Team Kappa",
    captainName: "Olivia Lopez",
    captainImage: "Ellipse900",
  },
  {
    id: 11,
    rank: 11,
    points: 9,
    teamName: "Team Lambda",
    captainName: "William Taylor",
    captainImage: "Ellipse910",
  },
  {
    id: 12,
    rank: 12,
    points: 8,
    teamName: "Team Mu",
    captainName: "Isabella Martinez",
    captainImage: "Ellipse920",
  },
  {
    id: 13,
    rank: 13,
    points: 7,
    teamName: "Team Nu",
    captainName: "James Anderson",
    captainImage: "Ellipse930",
  },
  {
    id: 14,
    rank: 14,
    points: 6,
    teamName: "Team Xi",
    captainName: "Mia Wilson",
    captainImage: "Ellipse940",
  },
  {
    id: 15,
    rank: 15,
    points: 5,
    teamName: "Team Omicron",
    captainName: "Ethan Brown",
    captainImage: "Ellipse950",
  },
  {
    id: 16,
    rank: 16,
    points: 4,
    teamName: "Team Pi",
    captainName: "Ava Garcia",
    captainImage: "Ellipse960",
  },
  {
    id: 17,
    rank: 17,
    points: 3,
    teamName: "Team Rho",
    captainName: "Liam Rodriguez",
    captainImage: "Ellipse970",
  },
  {
    id: 18,
    rank: 18,
    points: 2,
    teamName: "Team Sigma",
    captainName: "Charlotte Hernandez",
    captainImage: "Ellipse980",
  },
  {
    id: 19,
    rank: 19,
    points: 1,
    teamName: "Team Tau",
    captainName: "Noah Lopez",
    captainImage: "Ellipse990",
  },
  {
    id: 20,
    rank: 20,
    points: 0,
    teamName: "Team Upsilon",
    captainName: "Amelia Smith",
    captainImage: "Ellipse1000",
  },
  {
    id: 21,
    rank: 21,
    points: 1,
    teamName: "Team Phi",
    captainName: "Elijah Johnson",
    captainImage: "Ellipse1010",
  },
  {
    id: 22,
    rank: 22,
    points: 2,
    teamName: "Team Chi",
    captainName: "Harper Martinez",
    captainImage: "Ellipse1020",
  },
  {
    id: 23,
    rank: 23,
    points: 3,
    teamName: "Team Psi",
    captainName: "Benjamin Brown",
    captainImage: "Ellipse1030",
  },
  {
    id: 24,
    rank: 24,
    points: 4,
    teamName: "Team Omega",
    captainName: "Evelyn Wilson",
    captainImage: "Ellipse1040",
  },
  {
    id: 25,
    rank: 25,
    points: 5,
    teamName: "Team Alpha Prime",
    captainName: "Logan Anderson",
    captainImage: "Ellipse1050",
  },
  {
    id: 26,
    rank: 26,
    points: 6,
    teamName: "Team Beta Prime",
    captainName: "Ella Martinez",
    captainImage: "Ellipse1060",
  },
  {
    id: 27,
    rank: 27,
    points: 7,
    teamName: "Team Gamma Prime",
    captainName: "Ryan Johnson",
    captainImage: "Ellipse1070",
  },
  {
    id: 28,
    rank: 28,
    points: 8,
    teamName: "Team Delta Prime",
    captainName: "Grace Wilson",
    captainImage: "Ellipse1080",
  },
  {
    id: 29,
    rank: 29,
    points: 9,
    teamName: "Team Epsilon Prime",
    captainName: "Lucas Garcia",
    captainImage: "Ellipse1090",
  },
  {
    id: 30,
    rank: 30,
    points: 10,
    teamName: "Team Zeta Prime",
    captainName: "Avery Johnson",
    captainImage: "Ellipse1100",
  },
  {
    id: 31,
    rank: 31,
    points: 11,
    teamName: "Team Eta Prime",
    captainName: "Luna Martinez",
    captainImage: "Ellipse1110",
  },
  {
    id: 32,
    rank: 32,
    points: 12,
    teamName: "Team Theta Prime",
    captainName: "Jackson Brown",
    captainImage: "Ellipse1120",
  },
  {
    id: 33,
    rank: 33,
    points: 13,
    teamName: "Team Iota Prime",
    captainName: "Harper Wilson",
    captainImage: "Ellipse1130",
  },
  {
    id: 34,
    rank: 34,
    points: 14,
    teamName: "Team Kappa Prime",
    captainName: "Liam Garcia",
    captainImage: "Ellipse1140",
  },
  {
    id: 35,
    rank: 35,
    points: 15,
    teamName: "Team Lambda Prime",
    captainName: "Addison Martinez",
    captainImage: "Ellipse1150",
  },
  {
    id: 36,
    rank: 36,
    points: 16,
    teamName: "Team Mu Prime",
    captainName: "Elijah Johnson",
    captainImage: "Ellipse1160",
  },
  {
    id: 37,
    rank: 37,
    points: 17,
    teamName: "Team Nu Prime",
    captainName: "Scarlett Garcia",
    captainImage: "Ellipse1170",
  },
  {
    id: 38,
    rank: 38,
    points: 18,
    teamName: "Team Xi Prime",
    captainName: "Mason Martinez",
    captainImage: "Ellipse1180",
  },
  {
    id: 39,
    rank: 39,
    points: 19,
    teamName: "Team Omicron Prime",
    captainName: "Aria Brown",
    captainImage: "Ellipse1190",
  },
  {
    id: 40,
    rank: 40,
    points: 20,
    teamName: "Team Pi Prime",
    captainName: "Carter Wilson",
    captainImage: "Ellipse1200",
  },
  {
    id: 41,
    rank: 41,
    points: 21,
    teamName: "Team Rho Prime",
    captainName: "Eva Garcia",
    captainImage: "Ellipse1210",
  },
  {
    id: 42,
    rank: 42,
    points: 22,
    teamName: "Team Sigma Prime",
    captainName: "Mateo Johnson",
    captainImage: "Ellipse1220",
  },
  {
    id: 43,
    rank: 43,
    points: 23,
    teamName: "Team Tau Prime",
    captainName: "Zoe Martinez",
    captainImage: "Ellipse1230",
  },
  {
    id: 44,
    rank: 44,
    points: 24,
    teamName: "Team Upsilon Prime",
    captainName: "Jayden Brown",
    captainImage: "Ellipse1240",
  },
  {
    id: 45,
    rank: 45,
    points: 25,
    teamName: "Team Phi Prime",
    captainName: "Madison Wilson",
    captainImage: "Ellipse1250",
  },
];
