import {
  IAllProject,
  IAllTeams,
  IAllUsers,
  IPointsTable,
  ITeamMember,
} from "./Interface/HackathonInterface";

export const AllUsers: IAllUsers[] = [
  {
    Id: 1,
    Name: "John Doe",
    Email: "likitha.k@Technovert.com",
    EmployeeId: "EMP001",
    Department: 101,
    ProfilePic: "Software Engineer",
    Role: "Admin",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 2,
    Name: "Jane Smith",
    Email: "jane.smith@example.com",
    EmployeeId: "EMP002",
    Department: 2,
    ProfilePic: "Data Analyst",
    Role: "Analyst",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 3,
    Name: "Alice Johnson",
    Email: "alice.johnson@example.com",
    EmployeeId: "EMP003",
    Department: 1,
    ProfilePic: "UI/UX Designer",
    Role: "Designer",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 4,
    Name: "Bob Williams",
    Email: "bob.williams@example.com",
    EmployeeId: "EMP004",
    Department: 2,
    ProfilePic: "Project Manager",
    Role: "Manager",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 5,
    Name: "Emily Brown",
    Email: "emily.brown@example.com",
    EmployeeId: "EMP005",
    Department: 2,
    ProfilePic: "Marketing Specialist",
    Role: "Specialist",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 6,
    Name: "Michael Davis",
    Email: "michael.davis@example.com",
    EmployeeId: "EMP006",
    Department: 2,
    ProfilePic: "Financial Analyst",
    Role: "Analyst",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 7,
    Name: "Sarah Wilson",
    Email: "sarah.wilson@example.com",
    EmployeeId: "EMP007",
    Department: 1,
    ProfilePic: "HR Manager",
    Role: "Manager",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 8,
    Name: "David Martinez",
    Email: "david.martinez@example.com",
    EmployeeId: "EMP008",
    Department: 2,
    ProfilePic: "Software Developer",
    Role: "Developer",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 9,
    Name: "Olivia Taylor",
    Email: "olivia.taylor@example.com",
    EmployeeId: "EMP009",
    Department: 1,
    ProfilePic: "System Administrator",
    Role: "Administrator",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 10,
    Name: "James Moore",
    Email: "james.moore@example.com",
    EmployeeId: "EMP010",
    Department: 2,
    ProfilePic: "Data Scientist",
    Role: "Scientist",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 11,
    Name: "Sophia Clark",
    Email: "sophia.clark@example.com",
    EmployeeId: "EMP011",
    Department: 2,
    ProfilePic: "Quality Assurance Analyst",
    Role: "Analyst",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 12,
    Name: "Daniel Lee",
    Email: "daniel.lee@example.com",
    EmployeeId: "EMP012",
    Department: 2,
    ProfilePic: "Network Engineer",
    Role: "Engineer",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 13,
    Name: "Ava Rodriguez",
    Email: "ava.rodriguez@example.com",
    EmployeeId: "EMP013",
    Department: 2,
    ProfilePic: "Content Writer",
    Role: "Writer",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 14,
    Name: "Ethan Hall",
    Email: "ethan.hall@example.com",
    EmployeeId: "EMP014",
    Department: 2,
    ProfilePic: "Business Analyst",
    Role: "Analyst",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 15,
    Name: "Mia Garcia",
    Email: "mia.garcia@example.com",
    EmployeeId: "EMP015",
    Department: 2,
    ProfilePic: "Graphic Designer",
    Role: "Designer",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 16,
    Name: "Likitha Kattamudi",
    Email: "likitha.k@example.com",
    EmployeeId: "EMP016",
    Department: 2,
    ProfilePic: "Technical Support Specialist",
    Role: "Admin",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 17,
    Name: "Isabella Hernandez",
    Email: "isabella.hernandez@example.com",
    EmployeeId: "EMP017",
    Department: 2,
    ProfilePic: "Product Manager",
    Role: "Manager",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 18,
    Name: "William Young",
    Email: "william.young@example.com",
    EmployeeId: "EMP018",
    Department: 2,
    ProfilePic: "Sales Representative",
    Role: "Representative",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 19,
    Name: "Rohith Dudam",
    Email: "rohith.d@Technovert.com",
    EmployeeId: "EMP019",
    Department: 2,
    ProfilePic: "Customer Service Representative",
    Role: "Admin",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
  {
    Id: 20,
    Name: "Liam Rivera",
    Email: "liam.rivera@example.com",
    EmployeeId: "EMP020",
    Department: 2,
    ProfilePic: "Legal Advisor",
    Role: "Admin",
    IsRegistered: true,
    RegisteredDate: new Date(),
  },
];
console.log(AllUsers);

export const AllProject: IAllProject[] = [
  {
    Id: 1,
    ProjectName: "Project 1",
    Description: "Description of Project 1",
    ProjectStatus: 1,
    DetailedDescription: "Detailed description of Project 1",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 1",
    TeamId: 1,
  },
  {
    Id: 2,
    ProjectName: "Project 2",
    Description: "Description of Project 2",
    ProjectStatus: 2,
    DetailedDescription: "Detailed description of Project 2",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 2",
    TeamId: 2,
  },
  {
    Id: 3,
    ProjectName: "Project 3",
    Description: "Description of Project 3",
    ProjectStatus: 3,
    DetailedDescription: "Detailed description of Project 3",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 3",
    TeamId: 3,
  },
  {
    Id: 4,
    ProjectName: "Project 4",
    Description: "Description of Project 4",
    ProjectStatus: 4,
    DetailedDescription: "Detailed description of Project 4",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 4",
    TeamId: 4,
  },
  {
    Id: 5,
    ProjectName: "Project 5",
    Description: "Description of Project 5",
    ProjectStatus: 5,
    DetailedDescription: "Detailed description of Project 5",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 5",
    TeamId: 5,
  },
  {
    Id: 6,
    ProjectName: "Project 6",
    Description: "Description of Project 6",
    ProjectStatus: 1,
    DetailedDescription: "Detailed description of Project 6",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 6",
    TeamId: 6,
  },
  {
    Id: 7,
    ProjectName: "Project 7",
    Description: "Description of Project 7",
    ProjectStatus: 2,
    DetailedDescription: "Detailed description of Project 7",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 7",
    TeamId: 7,
  },
  {
    Id: 8,
    ProjectName: "Project 8",
    Description: "Description of Project 8",
    ProjectStatus: 3,
    DetailedDescription: "Detailed description of Project 8",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 8",
    TeamId: 8,
  },
  {
    Id: 9,
    ProjectName: "Project 9",
    Description: "Description of Project 9",
    ProjectStatus: 4,
    DetailedDescription: "Detailed description of Project 9",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 9",
    TeamId: 9,
  },
  {
    Id: 10,
    ProjectName: "Project 10",
    Description: "Description of Project 10",
    ProjectStatus: 5,
    DetailedDescription: "Detailed description of Project 10",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 10",
    TeamId: 10,
  },
];

console.log(AllProject);

export const AllTeams: IAllTeams[] = [
  { Id: 1, TeamName: "Team 1", TeamLogo: "logo_url_for_team_1" },
  { Id: 2, TeamName: "Team 2", TeamLogo: "logo_url_for_team_2" },
  { Id: 3, TeamName: "Team 3", TeamLogo: "logo_url_for_team_3" },
  { Id: 4, TeamName: "Team 4", TeamLogo: "logo_url_for_team_4" },
  { Id: 5, TeamName: "Team 5", TeamLogo: "logo_url_for_team_5" },
  { Id: 6, TeamName: "Team 6", TeamLogo: "logo_url_for_team_6" },
  { Id: 7, TeamName: "Team 7", TeamLogo: "logo_url_for_team_7" },
  { Id: 8, TeamName: "Team 8", TeamLogo: "logo_url_for_team_8" },
  { Id: 9, TeamName: "Team 9", TeamLogo: "logo_url_for_team_9" },
  { Id: 10, TeamName: "Team 10", TeamLogo: "logo_url_for_team_10" },
  { Id: 11, TeamName: "Team 11", TeamLogo: "logo_url_for_team_11" },
  { Id: 12, TeamName: "Team 12", TeamLogo: "logo_url_for_team_12" },
  { Id: 13, TeamName: "Team 13", TeamLogo: "logo_url_for_team_13" },
  { Id: 14, TeamName: "Team 14", TeamLogo: "logo_url_for_team_14" },
  { Id: 15, TeamName: "Team 15", TeamLogo: "logo_url_for_team_15" },
  { Id: 16, TeamName: "Team 16", TeamLogo: "logo_url_for_team_16" },
  { Id: 17, TeamName: "Team 17", TeamLogo: "logo_url_for_team_17" },
  { Id: 18, TeamName: "Team 18", TeamLogo: "logo_url_for_team_18" },
  { Id: 19, TeamName: "Team 19", TeamLogo: "logo_url_for_team_19" },
  { Id: 20, TeamName: "Team 20", TeamLogo: "logo_url_for_team_20" },
];

console.log(AllTeams);
export const TeamMember: ITeamMember[] = [
  { Id: 1, TeamId: 1, PersonId: 1, Role: 1, IsAdmin: true },
  { Id: 2, TeamId: 1, PersonId: 2, Role: 2, IsAdmin: false },
  { Id: 3, TeamId: 2, PersonId: 3, Role: 1, IsAdmin: true },
  { Id: 4, TeamId: 2, PersonId: 4, Role: 2, IsAdmin: false },
  { Id: 5, TeamId: 3, PersonId: 5, Role: 1, IsAdmin: true },
  { Id: 6, TeamId: 3, PersonId: 6, Role: 2, IsAdmin: false },
  { Id: 7, TeamId: 4, PersonId: 7, Role: 1, IsAdmin: true },
  { Id: 8, TeamId: 4, PersonId: 8, Role: 2, IsAdmin: false },
  { Id: 9, TeamId: 5, PersonId: 9, Role: 1, IsAdmin: true },
  { Id: 10, TeamId: 5, PersonId: 10, Role: 2, IsAdmin: false },
  { Id: 11, TeamId: 6, PersonId: 11, Role: 1, IsAdmin: true },
  { Id: 12, TeamId: 6, PersonId: 12, Role: 2, IsAdmin: false },
  { Id: 13, TeamId: 7, PersonId: 13, Role: 1, IsAdmin: true },
  { Id: 14, TeamId: 7, PersonId: 14, Role: 2, IsAdmin: false },
  { Id: 15, TeamId: 8, PersonId: 15, Role: 1, IsAdmin: true },
  { Id: 16, TeamId: 8, PersonId: 16, Role: 2, IsAdmin: false },
  { Id: 17, TeamId: 9, PersonId: 17, Role: 1, IsAdmin: true },
  { Id: 18, TeamId: 9, PersonId: 18, Role: 2, IsAdmin: false },
  { Id: 19, TeamId: 10, PersonId: 19, Role: 1, IsAdmin: true },
  { Id: 20, TeamId: 10, PersonId: 20, Role: 2, IsAdmin: false },
];
console.log(TeamMember);

export const PointsTable: IPointsTable[] = [
  {
    Id: 1,
    TeamId: 1,
    Team: "Team A",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 2,
    TeamId: 2,
    Team: "Team B",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 3,
    TeamId: 3,
    Team: "Team C",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 4,
    TeamId: 4,
    Team: "Team D",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 5,
    TeamId: 5,
    Team: "Team E",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 6,
    TeamId: 6,
    Team: "Team F",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 7,
    TeamId: 7,
    Team: "Team G",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 8,
    TeamId: 8,
    Team: "Team H",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 9,
    TeamId: 9,
    Team: "Team I",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 10,
    TeamId: 10,
    Team: "Team J",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 11,
    TeamId: 11,
    Team: "Team K",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 12,
    TeamId: 12,
    Team: "Team L",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 13,
    TeamId: 13,
    Team: "Team M",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 14,
    TeamId: 14,
    Team: "Team N",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 15,
    TeamId: 15,
    Team: "Team O",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 16,
    TeamId: 16,
    Team: "Team P",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 17,
    TeamId: 17,
    Team: "Team Q",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 18,
    TeamId: 18,
    Team: "Team R",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 19,
    TeamId: 19,
    Team: "Team S",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 20,
    TeamId: 20,
    Team: "Team T",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
];

console.log(PointsTable);
