import {
  IAllProject,
  IAllTeams,
  IAllUsers,
  IPointsTable,
  ITeamMember,
} from "./Interface/HackathonInterface";

export const AllUsers: IAllUsers[] = [
  {
    id: 1,
    name: "John Doe",
    email: "likitha.k@Technovert.com",
    employeeId: "EMP001",
    department: 101,
    profilePicture: "Software Engineer",
    role: "Admin",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    employeeId: "EMP002",
    department: 2,
    profilePicture: "Data Analyst",
    role: "Analyst",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    employeeId: "EMP003",
    department: 1,
    profilePicture: "UI/UX Designer",
    role: "Designer",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 4,
    name: "Bob Williams",
    email: "bob.williams@example.com",
    employeeId: "EMP004",
    department: 2,
    profilePicture: "Project Manager",
    role: "Manager",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 5,
    name: "Emily Brown",
    email: "emily.brown@example.com",
    employeeId: "EMP005",
    department: 2,
    profilePicture: "Marketing Specialist",
    role: "Specialist",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 6,
    name: "Michael Davis",
    email: "michael.davis@example.com",
    employeeId: "EMP006",
    department: 2,
    profilePicture: "Financial Analyst",
    role: "Analyst",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 7,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    employeeId: "EMP007",
    department: 1,
    profilePicture: "HR Manager",
    role: "Manager",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 8,
    name: "David Martinez",
    email: "david.martinez@example.com",
    employeeId: "EMP008",
    department: 2,
    profilePicture: "Software Developer",
    role: "Developer",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 9,
    name: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    employeeId: "EMP009",
    department: 1,
    profilePicture: "System Administrator",
    role: "Administrator",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 10,
    name: "James Moore",
    email: "james.moore@example.com",
    employeeId: "EMP010",
    department: 2,
    profilePicture: "Data Scientist",
    role: "Scientist",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 11,
    name: "Sophia Clark",
    email: "sophia.clark@example.com",
    employeeId: "EMP011",
    department: 2,
    profilePicture: "Quality Assurance Analyst",
    role: "Analyst",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 12,
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    employeeId: "EMP012",
    department: 2,
    profilePicture: "Network Engineer",
    role: "Engineer",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 13,
    name: "Ava Rodriguez",
    email: "ava.rodriguez@example.com",
    employeeId: "EMP013",
    department: 2,
    profilePicture: "Content Writer",
    role: "Writer",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 14,
    name: "Ethan Hall",
    email: "ethan.hall@example.com",
    employeeId: "EMP014",
    department: 2,
    profilePicture: "Business Analyst",
    role: "Analyst",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 15,
    name: "Mia Garcia",
    email: "mia.garcia@example.com",
    employeeId: "EMP015",
    department: 2,
    profilePicture: "Graphic Designer",
    role: "Designer",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 16,
    name: "Likitha Kattamudi",
    email: "likitha.k@example.com",
    employeeId: "EMP016",
    department: 2,
    profilePicture: "Technical Support Specialist",
    role: "Admin",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 17,
    name: "Isabella Hernandez",
    email: "isabella.hernandez@example.com",
    employeeId: "EMP017",
    department: 2,
    profilePicture: "Product Manager",
    role: "Manager",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 18,
    name: "William Young",
    email: "william.young@example.com",
    employeeId: "EMP018",
    department: 2,
    profilePicture: "Sales Representative",
    role: "Representative",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 19,
    name: "Rohith Dudam",
    email: "rohith.d@Technovert.com",
    employeeId: "EMP019",
    department: 2,
    profilePicture: "Customer Service Representative",
    role: "Admin",
    isRegistered: true,
    registeredDate: new Date(),
  },
  {
    id: 20,
    name: "Liam Rivera",
    email: "liam.rivera@example.com",
    employeeId: "EMP020",
    department: 2,
    profilePicture: "Legal Advisor",
    role: "Admin",
    isRegistered: true,
    registeredDate: new Date(),
  },
];
console.log(AllUsers);

export const AllProject: IAllProject[] = [
  {
    Id: 1,
    ProjectName: "Project 1",
    Description: "Description of Project 1",
    ProjectStatus: 1,
    DetailedDescription: "Detailed description of Project 1",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 1",
    TeamId: 1,
  },
  {
    Id: 2,
    ProjectName: "Project 2",
    Description: "Description of Project 2",
    ProjectStatus: 2,
    DetailedDescription: "Detailed description of Project 2",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 2",
    TeamId: 2,
  },
  {
    Id: 3,
    ProjectName: "Project 3",
    Description: "Description of Project 3",
    ProjectStatus: 3,
    DetailedDescription: "Detailed description of Project 3",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 3",
    TeamId: 3,
  },
  {
    Id: 4,
    ProjectName: "Project 4",
    Description: "Description of Project 4",
    ProjectStatus: 4,
    DetailedDescription: "Detailed description of Project 4",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 4",
    TeamId: 4,
  },
  {
    Id: 5,
    ProjectName: "Project 5",
    Description: "Description of Project 5",
    ProjectStatus: 5,
    DetailedDescription: "Detailed description of Project 5",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 5",
    TeamId: 5,
  },
  {
    Id: 6,
    ProjectName: "Project 6",
    Description: "Description of Project 6",
    ProjectStatus: 1,
    DetailedDescription: "Detailed description of Project 6",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 6",
    TeamId: 6,
  },
  {
    Id: 7,
    ProjectName: "Project 7",
    Description: "Description of Project 7",
    ProjectStatus: 2,
    DetailedDescription: "Detailed description of Project 7",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 7",
    TeamId: 7,
  },
  {
    Id: 8,
    ProjectName: "Project 8",
    Description: "Description of Project 8",
    ProjectStatus: 3,
    DetailedDescription: "Detailed description of Project 8",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 8",
    TeamId: 8,
  },
  {
    Id: 9,
    ProjectName: "Project 9",
    Description: "Description of Project 9",
    ProjectStatus: 4,
    DetailedDescription: "Detailed description of Project 9",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 9",
    TeamId: 9,
  },
  {
    Id: 10,
    ProjectName: "Project 10",
    Description: "Description of Project 10",
    ProjectStatus: 5,
    DetailedDescription: "Detailed description of Project 10",
    ProjectRegisteredDate: new Date(),
    SubmittedDate: new Date(),
    PresentationDate: new Date(),
    Comments: "Comments for Project 10",
    TeamId: 10,
  },
];

console.log(AllProject);

export const AllTeams: IAllTeams[] = [
  { Id: 1, TeamName: "Team 1", TeamLogo: "logo_url_for_team_1" },
  { Id: 2, TeamName: "Team 2", TeamLogo: "logo_url_for_team_2" },
  { Id: 3, TeamName: "Team 3", TeamLogo: "logo_url_for_team_3" },
  { Id: 4, TeamName: "Team 4", TeamLogo: "logo_url_for_team_4" },
  { Id: 5, TeamName: "Team 5", TeamLogo: "logo_url_for_team_5" },
  { Id: 6, TeamName: "Team 6", TeamLogo: "logo_url_for_team_6" },
  { Id: 7, TeamName: "Team 7", TeamLogo: "logo_url_for_team_7" },
  { Id: 8, TeamName: "Team 8", TeamLogo: "logo_url_for_team_8" },
  { Id: 9, TeamName: "Team 9", TeamLogo: "logo_url_for_team_9" },
  { Id: 10, TeamName: "Team 10", TeamLogo: "logo_url_for_team_10" },
  { Id: 11, TeamName: "Team 11", TeamLogo: "logo_url_for_team_11" },
  { Id: 12, TeamName: "Team 12", TeamLogo: "logo_url_for_team_12" },
  { Id: 13, TeamName: "Team 13", TeamLogo: "logo_url_for_team_13" },
  { Id: 14, TeamName: "Team 14", TeamLogo: "logo_url_for_team_14" },
  { Id: 15, TeamName: "Team 15", TeamLogo: "logo_url_for_team_15" },
  { Id: 16, TeamName: "Team 16", TeamLogo: "logo_url_for_team_16" },
  { Id: 17, TeamName: "Team 17", TeamLogo: "logo_url_for_team_17" },
  { Id: 18, TeamName: "Team 18", TeamLogo: "logo_url_for_team_18" },
  { Id: 19, TeamName: "Team 19", TeamLogo: "logo_url_for_team_19" },
  { Id: 20, TeamName: "Team 20", TeamLogo: "logo_url_for_team_20" },
];

console.log(AllTeams);
export const TeamMember: ITeamMember[] = [
  { Id: 1, TeamId: 1, PersonId: 1, Role: 1, IsAdmin: true },
  { Id: 2, TeamId: 1, PersonId: 2, Role: 2, IsAdmin: false },
  { Id: 3, TeamId: 2, PersonId: 3, Role: 1, IsAdmin: true },
  { Id: 4, TeamId: 2, PersonId: 4, Role: 2, IsAdmin: false },
  { Id: 5, TeamId: 3, PersonId: 5, Role: 1, IsAdmin: true },
  { Id: 6, TeamId: 3, PersonId: 6, Role: 2, IsAdmin: false },
  { Id: 7, TeamId: 4, PersonId: 7, Role: 1, IsAdmin: true },
  { Id: 8, TeamId: 4, PersonId: 8, Role: 2, IsAdmin: false },
  { Id: 9, TeamId: 5, PersonId: 9, Role: 1, IsAdmin: true },
  { Id: 10, TeamId: 5, PersonId: 10, Role: 2, IsAdmin: false },
  { Id: 11, TeamId: 6, PersonId: 11, Role: 1, IsAdmin: true },
  { Id: 12, TeamId: 6, PersonId: 12, Role: 2, IsAdmin: false },
  { Id: 13, TeamId: 7, PersonId: 13, Role: 1, IsAdmin: true },
  { Id: 14, TeamId: 7, PersonId: 14, Role: 2, IsAdmin: false },
  { Id: 15, TeamId: 8, PersonId: 15, Role: 1, IsAdmin: true },
  { Id: 16, TeamId: 8, PersonId: 16, Role: 2, IsAdmin: false },
  { Id: 17, TeamId: 9, PersonId: 17, Role: 1, IsAdmin: true },
  { Id: 18, TeamId: 9, PersonId: 18, Role: 2, IsAdmin: false },
  { Id: 19, TeamId: 10, PersonId: 19, Role: 1, IsAdmin: true },
  { Id: 20, TeamId: 10, PersonId: 20, Role: 2, IsAdmin: false },
];
console.log(TeamMember);

export const PointsTable: IPointsTable[] = [
  {
    Id: 1,
    TeamId: 1,
    Team: "Team A",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 2,
    TeamId: 2,
    Team: "Team B",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 3,
    TeamId: 3,
    Team: "Team C",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 4,
    TeamId: 4,
    Team: "Team D",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 5,
    TeamId: 5,
    Team: "Team E",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 6,
    TeamId: 6,
    Team: "Team F",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 7,
    TeamId: 7,
    Team: "Team G",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 8,
    TeamId: 8,
    Team: "Team H",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 9,
    TeamId: 9,
    Team: "Team I",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 10,
    TeamId: 10,
    Team: "Team J",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 11,
    TeamId: 11,
    Team: "Team K",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 12,
    TeamId: 12,
    Team: "Team L",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 13,
    TeamId: 13,
    Team: "Team M",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 14,
    TeamId: 14,
    Team: "Team N",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 15,
    TeamId: 15,
    Team: "Team O",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 16,
    TeamId: 16,
    Team: "Team P",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 17,
    TeamId: 17,
    Team: "Team Q",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
  {
    Id: 18,
    TeamId: 18,
    Team: "Team R",
    RegistrationScore: 90,
    ProjectSubmissionScore: 88,
    ProjectDemoScore: 82,
    OverAllScore: 87,
  },
  {
    Id: 19,
    TeamId: 19,
    Team: "Team S",
    RegistrationScore: 85,
    ProjectSubmissionScore: 90,
    ProjectDemoScore: 80,
    OverAllScore: 88,
  },
  {
    Id: 20,
    TeamId: 20,
    Team: "Team T",
    RegistrationScore: 80,
    ProjectSubmissionScore: 85,
    ProjectDemoScore: 75,
    OverAllScore: 80,
  },
];

console.log(PointsTable);
