import { IProject } from "../Interfaces";

export const projects: IProject[] = [
    {
      id: 1,
      TeamName: "Team Alpha",
      descripition: "descripition for Team Alpha",
      Status: "Accepted",
      submittedOn: "2024-10-01",
    },
    {
      id: 2,
      TeamName: "Team Bravo",
      descripition: "descripition for Team Bravo",
      Status: "Pending",
      submittedOn: "2024-01-02",
    },
    {
      id: 3,
      TeamName: "Team Charlie",
      descripition: "descripition for Team Charlie",
      Status: "Accepted",
      submittedOn: "2024-01-03",
    },
    {
      id: 4,
      TeamName: "Team Delta",
      descripition: "descripition for Team Delta",
      Status: "Pending",
      submittedOn: "2024-01-04",
    },
    {
      id: 5,
      TeamName: "Team Echo",
      descripition: "descripition for Team Echo",
      Status: "Accepted",
      submittedOn: "2024-01-05",
    },
    {
      id: 6,
      TeamName: "Team Foxtrot",
      descripition: "descripition for Team Foxtrot",
      Status: "Pending",
      submittedOn: "2024-01-06",
    },
    {
      id: 7,
      TeamName: "Team Golf",
      descripition: "descripition for Team Golf",
      Status: "Accepted",
      submittedOn: "2024-01-07",
    },
    {
      id: 8,
      TeamName: "Team Hotel",
      descripition: "descripition for Team Hotel",
      Status: "Pending",
      submittedOn: "2024-01-08",
    },
    {
      id: 9,
      TeamName: "Team India",
      descripition: "descripition for Team India",
      Status: "Accepted",
      submittedOn: "2024-01-09",
    },
    {
      id: 10,
      TeamName: "Team Juliet",
      descripition: "descripition for Team Juliet",
      Status: "Pending",
      submittedOn: "2024-01-10",
    },
    {
      id: 11,
      TeamName: "Team Kilo",
      descripition: "descripition for Team Kilo",
      Status: "Accepted",
      submittedOn: "2024-01-11",
    },
    {
      id: 12,
      TeamName: "Team Lima",
      descripition: "descripition for Team Lima",
      Status: "Pending",
      submittedOn: "2024-01-12",
    },
    {
      id: 13,
      TeamName: "Team Mike",
      descripition: "descripition for Team Mike",
      Status: "Accepted",
      submittedOn: "2024-01-13",
    },
    {
      id: 14,
      TeamName: "Team November",
      descripition: "descripition for Team November",
      Status: "Pending",
      submittedOn: "2024-01-14",
    },
    {
      id: 15,
      TeamName: "Team Oscar",
      descripition: "descripition for Team Oscar",
      Status: "Accepted",
      submittedOn: "2024-01-15",
    },
  ];